[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Environment variables for production
# These will be used to generate the env-config.js file during build
[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://jnradnvjonrioaysceny.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpucmFkbnZqb25yaW9heXNjZW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4ODg1MjksImV4cCI6MjA2MzQ2NDUyOX0.-cYzAWXvKo7nXRYho0gxZIBPIEpoKkWp8LMZYL54boM"

# Redirect all requests to the Next.js app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
