[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Uncomment this section and add your Supabase URL and anon key if you want to hardcode them
# [context.production.environment]
#   NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url"
#   NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"

# Redirect all requests to the Next.js app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
