[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Environment variables for production
# These will be used to generate the env-config.js file during build
[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://atavqnshcrgkfvrcclnr.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0YXZxbnNoY3Jna2Z2cmNjbG5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTQ1NTgsImV4cCI6MjA2MzE3MDU1OH0.eucRbfB5S0tPv1dPc0xB64C1n8Uu1ndv7qofsv1LqVk"

# Redirect all requests to the Next.js app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
